import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icons: {icon: "https://i.ibb.co/FXJ2RL7/Screenshot-2024-01-10-104130-1.png"},
  title: "BucketBD",
  description: "Generated by AHMED HOSSAIN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
      <Navbar></Navbar>
        {children}
      {/* <Footer></Footer> */}
      </AuthProvider>
      <ToastContainer 
position="top-right"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light" />
      </body>
      
    </html>
  );
}
